### ISSUE TITLE
Error during Storage instance (self.carol)

### ISSUE THREAD

**Issue by JuvenalDuarte** [totvslabs/pyCarol#572]
The following error has been reported by a client when trying to instantiate a Storage object:

```
ERROR:pycarol.app.online_api:Exception on /api/currency [GET]Traceback (most recent call last): 
File "C:\Anaconda3\envs\contabil\lib\site-packages\flask\app.py", line 2073, in wsgi_appresponse = self.full_dispatch_request() 
File "C:\Anaconda3\envs\contabil\lib\site-packages\flask\app.py", line 1518, in full_dispatch_requestrv = self.handle_user_exception(e) 
File "C:\Anaconda3\envs\contabil\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_functionreturn cors_after_request(app.make_response(f(*args, **kwargs))) 
File "C:\Anaconda3\envs\contabil\lib\site-packages\flask\app.py", line 1516, in full_dispatch_requestrv = self.dispatch_request() 
File "C:\Anaconda3\envs\contabil\lib\site-packages\flask\app.py", line 1502, in dispatch_requestreturn self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) 
File "C:\Anaconda3\envs\contabil\lib\site-packages\pycarol\app\online_api.py", line 108, in appr = api() 
File "C:\Users\leandro.oliveira\Documents\Projetos\BA\Python\Painel_Contabil\ba-carol-app-online\docker-images\online\run_me.py", line 42, in currencyreturn filters.currency() 
File "C:\Users\leandro.oliveira\Documents\Projetos\BA\Python\Painel_Contabil\ba-carol-app-online\docker-images\online\filters.py", line 147, in currencypre = PreProcess(headers=self.request.headers) 
File "C:\Users\leandro.oliveira\Documents\Projetos\BA\Python\Painel_Contabil\ba-carol-app-online\docker-images\core\pre_process.py", line 58, in _init_self.storage = Storage(self.carol) 
File "C:\Anaconda3\envs\contabil\lib\site-packages\pycarol\storage.py", line 25, in _init_self._init_if_needed() 
File "C:\Anaconda3\envs\contabil\lib\site-packages\pycarol\storage.py", line 31, in _init_if_needed(Carolina.token.get('app_name', '') == self.carol.app_name) and \AttributeError: 'NoneType' object has no attribute 'get'
```

I checked the code and it looks like the token object is expiring during the evaluation of the boolean clauses on the lines below, which looks very weird!

```
if (Carolina.token is not None) and (Carolina.token.get('tenant_name', '') == self.carol.tenant['mdmName']) and \
   (Carolina.token.get('app_name', '') == self.carol.app_name) and \
   (datetime.utcnow() + timedelta(minutes=1) < datetime.fromtimestamp(Carolina.token.get('expirationTimestamp', 1)/1000.0)):
```
I also checked if any version of python doesn't implements short-circuit evaluation, but that doesn't seems to be the case.
The best idea I had so far is to surround this block with a try catch, like below. Any other idea on how to address this?

```
try:
    # In very specific cases token may expire between the evaluation of the and clauses, causing AttributeError
    # exceptions. Added the try catch to avoid crashing the apps and to force token to be generated again.
    if (Carolina.token is not None) and (Carolina.token.get('tenant_name', '') == self.carol.tenant['mdmName']) and \
    (Carolina.token.get('app_name', '') == self.carol.app_name) and \
    (datetime.utcnow() + timedelta(minutes=1) < datetime.fromtimestamp(Carolina.token.get('expirationTimestamp', 1)/1000.0)):
        pass
        # return
    else:
        Carolina.token = None

except AttributeError:
    Carolina.token = None
```

**Comment by darolt** [comment]
Closing all old issues. If required we can open them again.
